import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";
import "./globals.css";
import { Header } from "./_layout/Header";

export const metadata: Metadata = {
  title: "SnipHub",
  description: "Generated by create next app",
};

const noto = Noto_Sans_JP({
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={`${noto.className} antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
